prod:
  frontend_base_url:  http://by-examples.localhost
  backend_base_url:   http://admin.by-examples.localhost

staging:
  frontend_base_url:  http://by-examples.localhost
  backend_base_url:   http://admin.by-examples.localhost

dev:
  frontend_base_url:  http://by-examples.localhost
  backend_base_url:   http://admin.by-examples.localhost




all:
  pager_example_max_na_stronie: 2
  pager_project_max_na_stronie: 3
  pager_hint_max_na_stronie:    5